"use client";
import { useEffect, useState } from "react";
import { resetEvaluationState,runFixture } from "@/lib/board-engine.mjs";
const fixtures=[['normal-d1-a','첫날 · 100'],['normal-d1-b','같은 날 · 105'],['normal-d2','다음 날 · 120'],['timeout','느린 응답'],['auth-401','401 접근 거절'],['rate-429','429 호출 제한'],['offline','오프라인'],['schema-break','형식 변경'],['recover-d2','복구 · 다음 날']];
const errorText:Record<string,[string,string]>={timeout:['응답 시간이 초과됐습니다.','데이터 제공처가 늦게 응답했습니다. 잠시 후 다시 시도해 주세요.'],auth:['데이터 제공처가 요청을 거절했습니다.','원천의 접근 상태를 확인하고 다시 시도해 주세요.'],rate_limit:['요청 한도에 도달했습니다.','잠시 기다린 뒤 다시 시도해 주세요.'],offline:['네트워크에 연결할 수 없습니다.','연결을 확인하고 다시 시도해 주세요.'],schema_error:['데이터 형식이 변경됐습니다.','값을 확인할 수 없어 저장하지 않았습니다. 재시도 후에도 지속되면 원천을 확인해 주세요.'],upstream_error:['데이터 제공처에 오류가 발생했습니다.','잠시 후 다시 시도해 주세요.']};
function time(s:any){return s?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false}):'아직 기록 없음'}
function round(n:number){return Number(n.toFixed(2))}
export default function Home(){
 const [mode,setMode]=useState<'live'|'replay'>('live');const [live,setLive]=useState<any>(null);const [replay,setReplay]=useState<any>(resetEvaluationState());const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [runs,setRuns]=useState<any[]>([]);const [library,setLibrary]=useState<any>({});const [source,setSource]=useState<any>(null);
 useEffect(()=>{fetch('/source.json').then(r=>r.ok?r.json():null).then(setSource).catch(()=>{});fetch('/api/board').then(async r=>{const d:any=await r.json();if(!r.ok)throw new Error(d.error);setLive(d)}).catch(e=>setNotice(e.message));Promise.all(fixtures.map(async ([id])=>{const r=await fetch('/assets/t04/fixtures/'+id+'.json');if(!r.ok)throw Error('시험 자료 로드 실패');return [id,await r.json()]})).then(entries=>setLibrary(Object.fromEntries(entries))).catch(e=>setNotice(e.message));},[]);
 const state=mode==='live'?live:replay;const reading=state?.current_reading;const status=state?.status;const stale=status?.freshness==='stale';const rows=state?.daily_readings||[];const comparison=state?.last_comparison;const prev=rows.filter((r:any)=>r.record_date<reading?.record_date).at(-1);
 async function refresh(){setBusy(true);setNotice('');try{const r=await fetch('/api/board',{method:'POST'});const data:any=await r.json();if(!r.ok)throw new Error(data.error);setLive(data);setNotice(data.status?.freshness==='fresh'?'실제 조회 결과를 서버에 저장했습니다.':'조회에 실패했습니다. 마지막 정상값을 보존합니다.');}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 function check(next:any,f:any){const ex=f.expected;return (!ex.freshness||next.status?.freshness===ex.freshness)&&(!ex.error_code||next.status?.error_code===ex.error_code)&&(ex.row_count===undefined||next.daily_readings.length===ex.row_count)&&(ex.stored_value===undefined||next.current_reading?.normalized_value===ex.stored_value)&&(ex.delta===undefined||next.last_delta===ex.delta)}
 function play(id:string){const f=library[id];if(!f){setNotice('시험 자료를 불러오는 중입니다.');return;}const next=runFixture(replay,f);setReplay(next);setRuns(r=>[...r,{id:f.fixture_id,pass:check(next,f)}]);setNotice('공식 합성 fixture를 재생했습니다. 실제 기록은 별도로 보존됩니다.');}
 function reset(){setReplay(resetEvaluationState());setRuns([]);setNotice('합성 시험 상태를 초기화했습니다.');}
 function scenario(id:string){let s=resetEvaluationState();const log:any[]=[];for(const name of ['normal-d1-a','normal-d1-b',id]){if(!library[name])return;const f=library[name];s=runFixture(s,f);log.push({id:f.fixture_id,pass:check(s,f)});}setReplay(s);setRuns(log);setNotice('첫날 정상값 105를 준비한 뒤 실패를 재현했습니다.');}
 function download(){const content={note:'앱 보존 기록입니다. 플랫폼이 발급한 봉인 t04_day 영수증을 대신하지 않습니다.',...live};const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='seoul-live-records.json';a.click();URL.revokeObjectURL(url)}
 return <main>
 <header><a className="brand" href="/">◈ <span>진짜 정보판</span></a><span className="zone">SEOUL · KST / UTC+09:00</span></header>
 <section className="intro"><div><p className="eyebrow">EVERYDAY, HONEST DATA</p><h1>오늘의 기온.<br/><span>기록은 남고, 상태는 솔직하게.</span></h1><p className="sub">서울의 현재 시각 예보 기온을 매일 기록합니다.<br/>데이터가 오지 않을 때도 마지막 정상값과 그 이유를 보여드립니다.</p></div><div className="intro-note"><span>01 / 서울</span><strong>37.5665° N<br/>126.9780° E</strong><p>고정 좌표 · 개인정보 수집 없음<br/>MET Norway 현재 시각의 예보 기온</p></div></section>
 <nav className="tabs" aria-label="데이터 모드"><button className={mode==='live'?'selected':''} onClick={()=>{setMode('live');setNotice('')}}>실제 데이터 <span>LIVE</span></button><button className={mode==='replay'?'selected':''} onClick={()=>{setMode('replay');setNotice('')}}>실패 재현 <span>TEST</span></button><small>{mode==='live'?'실제 공개 원천 · 서버에 영구 저장':'공식 합성 데이터 · 실제 기록과 분리'}</small></nav>
 <div className="grid"><section className={'current panel '+(stale?'is-stale':'')}><div className="panel-top"><p className="eyebrow">{mode==='live'?'서울 · 현재 시각의 예보 기온':'공식 시험 · 합성 지수'}</p><span className={'badge '+(stale?'warn':'')}>{busy?'조회 중':stale?'● 오래된 값':reading?'● 정상':'○ 조회 대기'}</span></div><div className="value">{reading?reading.normalized_value:'—'}<span>{reading?reading.unit:mode==='live'?'°C':'pt'}</span></div>
 <div className="comparison">{comparison?.state==='comparable'?<><strong>{comparison.direction==='increase'?'↗ +':comparison.direction==='decrease'?'↘ −':'→ '}{round(comparison.magnitude)} {comparison.unit}</strong><span>{prev?.record_date} 기록 대비{prev&&reading&&new Date(reading.record_date).getTime()-new Date(prev.record_date).getTime()!==86400000?' · 이전 기록과 비교':' · 어제 대비'}</span></>:<span>{comparison?.state==='unit_mismatch'?'단위가 달라 비교할 수 없습니다.':'비교할 이전 날짜의 기록이 아직 없습니다.'}</span>}</div>
 {stale&&<div className="error" role="status"><strong>{errorText[status.error_code]?.[0]||'조회에 실패했습니다.'}</strong><p>{errorText[status.error_code]?.[1]}</p><small>마지막 정상값을 유지합니다. {status.retry_after_seconds?status.retry_after_seconds+'초 후 재시도':''}</small></div>}
 <div className="current-actions">{mode==='live'?<button className="primary" onClick={refresh} disabled={busy}>{busy?'조회하고 저장하는 중…':stale?'다시 시도 ↻':'지금 조회하고 기록하기 ↗'}</button>:stale?<button className="primary" onClick={()=>play('recover-d2')}>다시 시도 · 복구 재현 ↻</button>:<button className="primary" onClick={()=>play('normal-d1-a')}>첫날 정상값 재생 ↗</button>}<small>{reading?'마지막 정상 조회 '+time(reading.fetched_at):'첫 조회를 실행하면 기록이 시작됩니다.'}</small></div></section>
 <section className="context panel"><p className="eyebrow">DATA CONTEXT / 데이터 맥락</p><dl><dt>출처</dt><dd>{reading?reading.source_name:'MET Norway'} {reading&&mode==='live'&&<a href={reading.source_url} target="_blank" rel="noreferrer">원천 ↗</a>}</dd><dt>출처 데이터 시각</dt><dd>{time(reading?.source_time)}</dd><dt>조회 성공 시각</dt><dd>{time(reading?.fetched_at)}</dd><dt>기준 시간대</dt><dd>Asia/Seoul · KST (UTC+09:00)</dd><dt>기록 날짜</dt><dd>{reading?.record_date||'아직 기록 없음'}</dd></dl><p className="context-foot">출처 시각은 데이터의 기준 시각,<br/>조회 시각은 우리가 값을 받은 시각입니다.</p></section></div>
 <p className="notice" aria-live="polite">{notice}</p>
 <section className="history panel"><div className="section-heading"><div><p className="eyebrow">DAILY ARCHIVE</p><h2>하루에 한 줄, 일별 기록</h2></div><span className="count">{rows.length}건</span></div><p className="muted">같은 KST 날짜의 성공 조회는 기존 행을 갱신합니다. 다음 날짜에는 새 행이 생깁니다.</p><div className="table-wrap"><table><thead><tr><th>KST 날짜</th><th>저장값</th><th>출처 시각</th><th>조회 시각</th></tr></thead><tbody>{[...rows].reverse().map((row:any)=><tr key={row.record_id}><td>{row.record_date}</td><td className="number">{row.normalized_value} {row.unit}</td><td>{time(row.reading.source_time)}</td><td>{time(row.reading.fetched_at)}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">아직 기록이 없습니다.<br/><small>{mode==='live'?'지금 조회하면 오늘의 실제 기록이 저장됩니다.':'정상 fixture를 재생해 시험을 시작하세요.'}</small></div>}</div>
 {mode==='live'&&<div className="evidence-note"><strong>실제 날짜 증거: {new Set((live?.evidence||[]).map((e:any)=>e.reading.record_date)).size}일 기록</strong><p>서로 다른 실제 KST 날짜에 조회해야 이틀 기록이 완성됩니다. 플랫폼의 봉인 영수증 t04_day 2건은 별도로 발급받아 제출해야 합니다.</p><button onClick={download} disabled={!live}>보존 기록 JSON 내려받기 ↓</button><details><summary>갱신 전 값도 보존한 실제 조회 이력</summary><p>아래 이력은 앱이 저장한 값입니다. 플랫폼 봉인 영수증과 대조할 조회를 확인하세요.</p><div className="table-wrap"><table><thead><tr><th>조회 시각 (KST)</th><th>값</th><th>출처 시각</th></tr></thead><tbody>{(live?.evidence||[]).map((e:any)=><tr key={e.id}><td>{time(e.created_at)}</td><td>{e.reading.normalized_value} {e.reading.unit}</td><td>{time(e.reading.source_time)}</td></tr>)}</tbody></table></div></details></div>}
 </section>
 {mode==='replay'&&<section className="replay panel"><div className="section-heading"><div><p className="eyebrow">FAILURE LAB / 합성 시험</p><h2>값이 오지 않을 때를 확인합니다.</h2></div><button onClick={reset}>시험 초기화 ↻</button></div><p className="muted">실패 버튼은 매번 초기화 → 첫날 100 → 같은 날 105 → 해당 실패 순서로 실행합니다.</p><div className="failure-buttons">{fixtures.slice(3,8).map(([id,label])=><button key={id} onClick={()=>scenario(id)} disabled={!library[id]}>{label} ↗</button>)}</div><details><summary>개별 fixture 순서대로 재생하기</summary><div className="fixture-buttons">{fixtures.map(([id,label])=><button key={id} onClick={()=>play(id)} disabled={!library[id]}>{label}</button>)}</div></details><div className="test-state"><span>freshness <b>{status?.freshness||'none'}</b></span><span>error_code <b>{status?.error_code||'none'}</b></span><span>일별 행 <b>{rows.length}</b></span><span>변화 절대값 <b>{state?.last_delta??'—'}</b></span></div><ol className="runs">{runs.map((r,i)=><li key={i}><code>{r.id}</code><span className={r.pass?'pass':'fail'}>{r.pass?'PASS':'FAIL'}</span></li>)}</ol><a href="/assets/t04/README.md" target="_blank">공식 사용법 ↗</a> · <a href="/assets/t04/public-contract.json" target="_blank">판정 계약 ↗</a></section>}
 <details className="panel audit"><summary>원자료 · 정규화 저장값 · 화면값 대조</summary><p className="muted">화면은 저장된 정규화 값을 그대로 표시합니다. 원자료와 정규화 기록을 나란히 확인하세요.</p>{mode==='live'?(live?.raw_readings||[]).map((r:any)=><div className="audit-row" key={r.record_id}><div><h3>원자료</h3><pre>{JSON.stringify(r.raw,null,2)}</pre></div><div><h3>저장값 · 화면값 {r.reading.normalized_value} {r.reading.unit}</h3><pre>{JSON.stringify(r.reading,null,2)}</pre></div></div>):<pre>{JSON.stringify(replay,null,2)}</pre>}</details>
 <footer>{source&&<a href={source.url}>전체 소스 ZIP ↓</a>}<span>◈ 오늘의 진짜 정보판</span><p>서울 고정 위치 · MET Norway<br/>실패에도 값을 지우지 않는 작은 기록장.</p><a href="https://api.met.no/weatherapi/locationforecast/2.0/documentation" target="_blank" rel="noreferrer">데이터 원천 문서 ↗</a></footer>
 </main>
}
